# -*- coding: utf-8 -*-
"""Precificação Black-scholes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzd98IyB_9a-8kuurZbKitESa4Q6kNVT
"""

#Construção de modelo de precificação Black Scholes

#Fórmula - C = S0 * N(d1) - K . e^rT . N (d2)

import math
from scipy.stats import norm

#Variaveis

S = 100 # preço atual da ação
K = 100 # Strike (preço de exercicio)
T = 1 # tempo em anos
r = 0.04 # taxa de juros livre de risco
sigma = 0.2 # volatilidade anual

#Calculo do d1 e d2

d1 = (math.log(S / K) + (r + 0.05 * sigma**2) * T) / (sigma * math.sqrt(T))
d2 = d1 - sigma * math.sqrt(T)

#Calculo do preço de Call e Put

call_price = S * norm.cdf(d1) - K * math.exp(-r * T) * norm.cdf(d2)
put_price = K * math.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)

#Resultado
print(f"preço de CALL: {call_price:.2f}")
print(f"preço de PUT: {put_price:.2f}")

